### ISSUE TITLE
Extra hearts & extra cutlets

### ISSUE THREAD

**Issue by DavideBlade** [DavideBlade/Health#1]
[CHeesy](https://www.spigotmc.org/members/cheesy.76755/) [requires](https://www.spigotmc.org/resources/health.99340/reviews#review-464591-76755) to add the option to set an extra number of hearts for players with a command.

**Comment by CheesyN** [comment]
I can make a separate request for this but I was thinking it would be worth being able to have an additional cutlets as well if possible.

**Comment by DavideBlade** [comment]
This is interesting. I'll see what I can do (also based on what Minecraft allows).

**Comment by DavideBlade** [comment]
The maximum number of hearts can now be set in version 2.6.3 (https://github.com/DavideBlade/Health/commit/9b9488dfd3971e03307466a547f5d8401777eabd).

Regarding the number of cutlets, it seems that Minecraft does not support their modification. A new system should be designed to change the consumption of cutlets over time, so that it looks like the number of cutlets actually corresponds to a greater number (if for example instead of consuming 1 cutlet per minute you consume 0.5, it means that you have practically doubled their number), but as interesting as it might be at the moment I don't have time and anyway the plugin wants to remain simple, so in any case I won't implement it.

Thanks for the suggestions :slightly_smiling_face:
